def utils
pipeline {
    agent any 
    environment{
        PROJECT_DIR = "50-Ansible_integration_in_Jenkins"
    }
    stages {
        stage('__init__') {
            steps {
                script {
                    utils = load "${env.PROJECT_DIR}/utils.groovy"
                    // utils.getAnsibleServerIp()
                    env.ANSIBLE_SERVER = utils.getAnsibleServerIp()
                    echo ANSIBLE_SERVER
                }
                // sshagent(credentials: ['devops_ssh_priv'], executable: '') {
                //     withCredentials([sshUserPrivateKey(credentialsId: 'devops_ssh_priv', keyFileVariable: 'devops_ssh_priv_key')]) {
                //         sh 'ssh -o StrictHostKeyChecking=no ubuntu@$ANSIBLE_SERVER echo "hello"'
                //         sh 'rsync -av $devops_ssh_priv_key ubuntu@$ANSIBLE_SERVER:~/devops_ssh_priv_key'
                //         sh 'rsync -av $PROJECT_DIR/ansible ubuntu@$ANSIBLE_SERVER:~/'
                //         sh 'ssh ubuntu@$ANSIBLE_SERVER ls -al ~/ansible'
                //         withCredentials([usernamePassword(credentialsId: 'aws_acc_key_and_sec', passwordVariable: 'AWS_SECRET_ACCESS_KEY', usernameVariable: 'AWS_ACCESS_KEY_ID')]) {
                //             sh '''ssh ubuntu@$ANSIBLE_SERVER \
                //                 AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                //                 AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
                //                 ANSIBLE_CONFIG=ansible/ansible.cfg \
                //                 ansible-playbook -i ansible/dyn-hosts.aws_ec2.yaml ansible/deploy-on-workstations.yaml \
                //                 '''
                //         }
                //     }
                // }
            }
        }

        stage('Preparing Ansible Controller ') {
            utils.copyConfigsToAnsibleController()
        }

        stage('Running playbook for Workstations') {
            utils.copyConfigsToAnsibleController()
        }
    }

}
