def gs
pipeline {
    agent any 
    stages {
        stage('__init__') {
            steps {
                script {
                    echo "holding my place"
                    gs = load "utils.groovy"
                }
            }
        }
    }
}