def utils
pipeline {
    agent any 
    environment{
        SUBDIR = "50-Ansible_integration_in_Jenkins"
    }
    stages {
        stage('__init__') {
            steps {
                script {
                    utils = load "${env.SUBDIR}/utils.groovy"
                    // utils.getAnsibleServerIp()
                    env.ANSIBLE_SERVER = utils.getAnsibleServerIp()
                    echo ANSIBLE_SERVER
                }
                sshagent(credentials: ['devops_ssh_priv'], executable: '') {
                    def conn_snipped = '-o StrictHostKeyChecking=no ubuntu@$ANSIBLE_SERVER'
                   sh 'ssh $conn_snipped ls /' 
                }
            }
        }
    }
}
